### ISSUE TITLE
New non-deltachat icon for the store

### ISSUE THREAD

**Issue by Septias** [webxdc/store#189]
I want to create a new icon which doesn't show dc.

**Comment by r10s** [comment]
cool, i am also not too happy with the current icon and would have created sth. as well, but happily waiting for your ideas :)

a general note: to let the icon look "square" also if used in white bubbles, i'd not use plain white as background (as currently) unless there is a border or sth like that; we should try be a good example with the store and go for an icon that looks "square" in mostly all cases

**Comment by Septias** [comment]
Made some icons:
![icon4](https://github.com/webxdc/store/assets/39526136/7b03dbb6-a5c0-427b-b923-730f196b25e2)
![icon3](https://github.com/webxdc/store/assets/39526136/a64481a7-703d-4087-94cc-696856cb116d)
![icon2](https://github.com/webxdc/store/assets/39526136/fa98008e-62da-47fe-9f74-e13dcdcea97d)
![icon1](https://github.com/webxdc/store/assets/39526136/990d6366-ed22-447b-9b5d-5ff42c3d1e9c)

I still think none of them are good enough for the final version, but at least a start maybe. Feel free to also design some stuff @r10s.

**Comment by r10s** [comment]
if we want to go for a variation of the  "webxdc icon" with a "play" symbol, at a first glance, i find the first one too far away.

the other ones are interesting, but maybe have too many details. maybe the following variation?

&nbsp;

![simpler-rotated](https://github.com/webxdc/store/assets/9800740/e58b64d5-d88e-44c7-bdd8-60a99ac5f8f8)

&nbsp;

i also rotated the "play" button a little, so that its left border is parallel (roughly :) with the slash (without the rotation, there is an optical illusion for me that looks as if it falls to the left :) but not sure, just an idea

**Comment by Septias** [comment]
I also tried rotating it the way you did, but it didn't work for me. For your design though I think it fits pretty well :)
What did you mean with the square borders anyway? @r10s

**Comment by r10s** [comment]
i mentioned borders only if one _really_ want to have a #ffffff background. i would not do that here and i would also not add borders in case of these icons.

instead, we could a background that is close to #ffffff, so that we still have the square icon as for other webxdc apps and contrast to the bubbles, both, in dark and light mode. 

i am thinking of sth as the background in the sc icon that us used on github, ios and others: 
![](https://github.com/deltachat/deltachat-ios/blob/master/images/appicon.png)

**Comment by Septias** [comment]
I thought maybe a big border like the first icon could be nice, but this is already close to perfect I would say. So my suggestion is to just add this now and be happy. At some point, I would like to get an explanation for why we do not just allow transparent backgrounds because having to choose a color makes it very hard to find a good match for dark and light themes. But that can wait for some irl discussion as I'm sure you have good reason for that.

**Comment by r10s** [comment]
first, it is not the end of the world, if there is an icon with plain white background, i just do not want to give a not-so-good example with our flagship apps :)

> an explanation for why we do not just allow transparent backgrounds 

the reason is to give implementations the chance for a nice, uniform layout. if we would allow shaped icons or transparency, UI cannot eg. add the icons with a drop shadow or a border (or, of course, they can, but it will look not nice or uniform)

also, depending on host app, support of alpha channels and transparency may be more complicated that just drawing sth opaque (this is a minor reason, but still)

> because having to choose a color makes it very hard to find a good match for dark and light themes

that would be even harder for transparent icons. eg. on easily ends up with black on transparent  - that look good on white but turn invisible on black.

this is reasons, transparent icons have a contrasting border, if done well (see the delta chat icon)

there could be other approaches to deal with all that (see eg. the icon guides for apple or google), however, the current approach _"rectangular, no shape, no transparency"_ fulfils many aspects in an comparable easy way for both, hosts and webxdc apps
