### ISSUE TITLE
re-opening webxdc calls sendToChat() directly

### ISSUE THREAD

**Issue by r10s** [webxdc/store#91]
after sharing 2 webxdc and closing the store: on re-opening  the store, the store closes immediately and directly shows the the "share to" dialog

it seems as if somehow the "sendToChat" click is re-executed when re-opening

confirmed by @Simon-Laux and @hpk42 in chat

**Comment by r10s** [comment]
maybe this comes from updates being replayed on startup

**Comment by adbenitez** [comment]
alternatives:

1. don't launch sendToChat() directly but just download first then the share button becomes available

2. track if the download was started in the current session, then ignore download started in another session (session == the time since the app was opened) ex. by keeping an in-memory volatile state that will be discarded every time the app is closed, then if the download was not triggered in this session, don't call sendToChat(), this would also need to disable the other buttons while a download is in progress

option 1 sounds worth a try because also allows "saving for later" several apps at the same time, option 2 is simpler for user, a single click, a single action

**Comment by Septias** [comment]
I also like the second option more

**Comment by Simon-Laux** [comment]
I like the first option more and I dislike the second option so much that I would not use the app.
Please don't be too smart about it, you'll invite more bugs.

**Comment by Septias** [comment]
This depends on #76, would be nice to get in a review soon.
